name: trader
description: Stock Advisory Trader Application

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  toast:
  provider:
  firebase_auth:
  firebase_core:
  google_sign_in:
  firebase_database:
  firebase_messaging:
  firebase_storage:
  shared_preferences:
  google_fonts:
  flutter_spinkit:
  line_icons:
  url_launcher:
  permission_handler:
  android_intent:
  sliding_card:
  draw_graph:
  sliding_sheet:
  credit_card:
  connectivity:
  image_picker:
  razorpay_flutter:
  flutter_spinning_wheel:
  shake:
  cool_alert:
  intl:
  qr_code_scanner:
  flutter_local_notifications:
  qr_code_tools:
  package_info:
  shape_of_view:
  quick_actions:
  flutter_socket_io:
  platform_device_id:
  flutter_native_timezone:
  rxdart:
  timezone:
  flutter_signin_button:
  flutter_windowmanager: 0.0.2
  dart_ipify:
  web_socket_channel:
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  pinch_zoom_image_last: ^0.4.1
  uri_to_file: ^0.1.3
  path_provider:
  icon_shadow: ^1.0.1
  pin_code_fields: ^7.3.0
  share:
  flashy_tab_bar2:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/quicktrades.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/other/google_logo.png
    - assets/other/card_bg.jpg
    - assets/logo/quicktrades.png
    - assets/spin/wheel.png
    - assets/spin/pointer.png
    - assets/spin/shake.png
    - assets/brokers/5paisa.png
    - assets/other/error.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
